import { Geist, Geist_Mono } from "next/font/google";
import { Inter_Tight, Ms_Madi } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const interTight = Inter_Tight({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-inter-tight",
});

const msMadi = Ms_Madi({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-ms-madi",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interTight.variable} ${msMadi.variable} ${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-black`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
